function [pcm] =  CoM2D(q)
%%%%%%  PointsAtrias2D.m
%%%%  26-May-2015 21:58:14
%%%%
%%%% Authors(s): Griffin modified (Grizzle orignal)
%%%%
%%%%
[g,mTotal,L1,L2,L3,L4,m1,m2,m3,m4,Jcm1,Jcm2,Jcm3,Jcm4,ellzcm1,...
         ellzcm2,ellzcm3,ellzcm4,ellycm1,ellycm2,ellycm3,ellycm4,LT,mT,...
         JcmT,ellzcmT,ellycmT,mH,JcmH,K1,K2,Kd1,Kd2,Jrotor1,Jrotor2 ...
         Jgear1,Jgear2,R1, R2] = modelParametersAtrias_v05;
%%%%
%%%%[g mTotal L1 L2 L3 L4 m1 m2 m3 m4 Jcm1 Jcm2 Jcm3 Jcm4 ellzcm1 ellzcm2 ellzcm3 ellzcm4 ellycm1 ellycm2 ellycm3 ellycm4 LT mT JcmT ellzcmT ellycmT mH JcmH K1 K2 Kd1 Kd2 Jrotor1 Jrotor2 Jgear1  Jgear2 R1  R2] = modelParametersAtrias_v05;
%%%%
%%%%
yH=q(1);  
zH=q(2);  
qT=q(3);  
q1=q(4);  
q2=q(5);  
q1L=q(6);  
q2L=q(7);  
%%%%
%%%%
pcm=[yH + (m1*(ellycm1*cos(q1 + qT) - ellzcm1*sin(q1 + qT)) + m2*...
         (ellycm2*cos(q2 + qT) - ellzcm2*sin(q2 + qT)) + m1*(ellycm1*...
         cos(q1L + qT) - ellzcm1*sin(q1L + qT)) + m2*(ellycm2*...
         cos(q2L + qT) - ellzcm2*sin(q2L + qT)) + mT*(ellycmT*...
         cos(qT) - ellzcmT*sin(qT)) - m3*(L1*sin(q1 + qT) - ellycm3*...
         cos(q2 + qT) + ellzcm3*sin(q2 + qT)) - m4*(L2*...
         sin(q2 + qT) - ellycm4*cos(q1 + qT) + ellzcm4*sin(q1 + qT)) - m3*...
         (L1*sin(q1L + qT) - ellycm3*cos(q2L + qT) + ellzcm3*...
         sin(q2L + qT)) - m4*(L2*sin(q2L + qT) - ellycm4*...
         cos(q1L + qT) + ellzcm4*sin(q1L + qT)))/(2*m1 + 2*m2 + 2*m3 + 2*...
         m4 + mH + mT); (mH*zH + m1*(zH + ellzcm1*cos(q1 + qT) + ellycm1*...
         sin(q1 + qT)) + m2*(zH + ellzcm2*cos(q2 + qT) + ellycm2*...
         sin(q2 + qT)) + m1*(zH + ellzcm1*cos(q1L + qT) + ellycm1*...
         sin(q1L + qT)) + m2*(zH + ellzcm2*cos(q2L + qT) + ellycm2*...
         sin(q2L + qT)) + m3*(zH + L1*cos(q1 + qT) + ellzcm3*...
         cos(q2 + qT) + ellycm3*sin(q2 + qT)) + m4*(zH + L2*...
         cos(q2 + qT) + ellzcm4*cos(q1 + qT) + ellycm4*sin(q1 + qT)) + m3*...
         (zH + L1*cos(q1L + qT) + ellzcm3*cos(q2L + qT) + ellycm3*...
         sin(q2L + qT)) + m4*(zH + L2*cos(q2L + qT) + ellzcm4*...
         cos(q1L + qT) + ellycm4*sin(q1L + qT)) + mT*(zH + ellzcmT*...
         cos(qT) + ellycmT*sin(qT)))/(2*m1 + 2*m2 + 2*m3 + 2*...
         m4 + mH + mT)];
return