function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (22-Dec-2017 00:16:59)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = (var(1).*sum(((((var(2:1:1201).^2.0)+((((var(1203:1:2402).^2.0)+(var(2404:1:3603).^2.0))+(var(3605:1:4804).^2.0))+(var(4806:1:6005).^2.0)))+((var(3:1:1202).^2.0)+((((var(1204:1:2403).^2.0)+(var(2405:1:3604).^2.0))+(var(3606:1:4805).^2.0))+(var(4807:1:6006).^2.0))))./2.0)));
end % ipoptObjective